### ISSUE TITLE
Easy "triggered once"

### ISSUE THREAD

**Issue by sainf** [silvestreh/onScreen#42]
Can be an easy way to do an trigger just once per element on the "enter" event.  

I'm using something like this:

```
<p class="anim">foo</p>
<p class="anim">foo</p>

os.on('enter', '.anim', (element) => {
  element.style.color = 'red'
})
```

I saw the [issue #29 ](https://github.com/silvestreh/onScreen/issues/29), but I'm not using jQuery.

Can this become an "enhancement"

**Comment by silvestreh** [comment]
A quick workaround could be…

```javascript
os.on('enter', '.anim', (element) => {
    element.style.color = 'red';
    os.off('enter', '.anim');
});
```

I could probably add a `.once` method to do exactly this.

**Comment by sainf** [comment]
Sorry my problem is per element.

```
<p class="anim">foo</p>
<p class="anim">foo</p>


os.on('enter', '.anim', (element) => {
    element.style.color = 'red';
    os.off('enter', '.anim');
});
```
It does not trigger on the second element...

In the [Issue #29](https://github.com/silvestreh/onScreen/issues/29) the solution was giving a control class to the element.

Can it become more easy?

**Comment by silvestreh** [comment]
Hmmm… might not be as simple then… I guess the best approach (at least for now) is still the one suggested in #29.

```javascript
os.on('enter', '.anim', (element) => {
    if (!element.entered) {
        element.style.color = 'red';
    }

    element.entered = true;
});
```

`element` in the above snippet is a `HTMLEelement` instance. You can add new, arbitrary, properties to an object, and that's exactly what I'm doing with `element.entered`.

Since the property doesn't exists at first, `!element.entered` will coerce to `true` enabling you to do your thing within that `IF` block.

Once that's done it'll create the property in the `HTMLElement` and set it to `true` so the `IF` block won't ever run again.

**Comment by sainf** [comment]
Your snippet is a simple and elegant solution.
Very well explained, Thanks.
